### ISSUE TITLE
Uploading a demo after the first results in "Error: Only a single offscreen document may be created."

### ISSUE THREAD

**Issue by deubel** [CSNADESgg/faceit-to-leetify-extension#1]
![image](https://github.com/CSNADESgg/faceit-to-leetify-extension/assets/3678621/939b95ff-0b5f-43a5-bd28-4f75a69d4fdb)

See screenshot. First upload worked as expected. Any subsequent uploads result in this error. Restarting browser did not fix this.

**Comment by Cretezy** [comment]
Thank you for the report! I've found the issue and fixed it in https://github.com/CSNADESgg/faceit-to-leetify-extension/commit/edb5c313d7be4d46741098c7c8dba354d1e54cd8. I just released https://github.com/CSNADESgg/faceit-to-leetify-extension/releases/tag/v0.3.1 to the Chrome extension store with this fix. It should be available within 24h (will update here).

**Comment by deubel** [comment]
Thank you for the quick fix, awesome plugin!

**Comment by Cretezy** [comment]
Fix is out for Chrome
