### ISSUE TITLE
Upload to Leetify button is not showing

### ISSUE THREAD

**Issue by Maksim-Nikolaev** [CSNADESgg/faceit-to-leetify-extension#3]
Today I noticed that Upload to Leetify button is not showing. 
![image](https://github.com/CSNADESgg/faceit-to-leetify-extension/assets/45855362/72023faa-74ef-43db-b047-c6317973ae9b)

In console it shows that it was loaded. I don't have more details unfortunately
![image](https://github.com/CSNADESgg/faceit-to-leetify-extension/assets/45855362/51f09afd-c664-413a-8dd6-6204a5cc1630)

**Comment by Cretezy** [comment]
A fix has been released and should be out within 24h. Please try again with version 0.4.3!
